[2025-10-31T10:52:46.201+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-31T10:52:46.228+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_bike_db.refresh_bike_db scheduled__2025-10-31T10:51:00+00:00 [queued]>
[2025-10-31T10:52:46.242+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_bike_db.refresh_bike_db scheduled__2025-10-31T10:51:00+00:00 [queued]>
[2025-10-31T10:52:46.244+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-10-31T10:52:46.264+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): refresh_bike_db> on 2025-10-31 10:51:00+00:00
[2025-10-31T10:52:46.277+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'refresh_bike_db', 'refresh_bike_db', 'scheduled__2025-10-31T10:51:00+00:00', '--job-id', '450', '--raw', '--subdir', 'DAGS_FOLDER/refresh_bike_db.py', '--cfg-path', '/tmp/tmpe9g3fct_']
[2025-10-31T10:52:46.281+0000] {standard_task_runner.py:105} INFO - Job 450: Subtask refresh_bike_db
[2025-10-31T10:52:46.283+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=178) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-31T10:52:46.284+0000] {standard_task_runner.py:72} INFO - Started process 181 to run task
[2025-10-31T10:52:46.375+0000] {task_command.py:467} INFO - Running <TaskInstance: refresh_bike_db.refresh_bike_db scheduled__2025-10-31T10:51:00+00:00 [running]> on host caf37e8f6386
[2025-10-31T10:52:46.559+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='refresh_bike_db' AIRFLOW_CTX_TASK_ID='refresh_bike_db' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T10:51:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T10:51:00+00:00'
[2025-10-31T10:52:46.560+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-31T10:52:46.613+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T10:52:46.615+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n          set -euxo pipefail\n          cd "$AIRFLOW_HOME/plugins"\n          python gather_bike_data.py\n        ']
[2025-10-31T10:52:46.633+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T10:52:46.634+0000] {subprocess.py:93} INFO - + cd /opt/***/plugins
[2025-10-31T10:52:46.635+0000] {subprocess.py:93} INFO - + python gather_bike_data.py
[2025-10-31T10:52:48.247+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-31T10:52:48.248+0000] {subprocess.py:93} INFO -   File "/opt/***/plugins/gather_bike_data.py", line 14, in <module>
[2025-10-31T10:52:48.250+0000] {subprocess.py:93} INFO -     DB_PORT = int(os.getenv("DB_PORT"))
[2025-10-31T10:52:48.251+0000] {subprocess.py:93} INFO -               ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-10-31T10:52:48.252+0000] {subprocess.py:93} INFO - TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-10-31T10:52:48.386+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T10:52:48.423+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T10:52:48.440+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=refresh_bike_db, task_id=refresh_bike_db, run_id=scheduled__2025-10-31T10:51:00+00:00, execution_date=20251031T105100, start_date=20251031T105246, end_date=20251031T105248
[2025-10-31T10:52:48.474+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-31T10:52:48.475+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 450 for task refresh_bike_db (Bash command failed. The command returned a non-zero exit code 1.; 181)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T10:52:48.512+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-31T10:52:48.544+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T10:52:48.549+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
