[2025-10-31T08:28:01.073+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-31T08:28:01.096+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_bike_db.install_requirements scheduled__2025-10-31T08:27:00+00:00 [queued]>
[2025-10-31T08:28:01.108+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_bike_db.install_requirements scheduled__2025-10-31T08:27:00+00:00 [queued]>
[2025-10-31T08:28:01.109+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-10-31T08:28:01.129+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): install_requirements> on 2025-10-31 08:27:00+00:00
[2025-10-31T08:28:01.141+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6268) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-31T08:28:01.142+0000] {standard_task_runner.py:72} INFO - Started process 6270 to run task
[2025-10-31T08:28:01.140+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'refresh_bike_db', 'install_requirements', 'scheduled__2025-10-31T08:27:00+00:00', '--job-id', '340', '--raw', '--subdir', 'DAGS_FOLDER/refresh_bike_db.py', '--cfg-path', '/tmp/tmp7r2jaffm']
[2025-10-31T08:28:01.144+0000] {standard_task_runner.py:105} INFO - Job 340: Subtask install_requirements
[2025-10-31T08:28:01.172+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-31T08:28:01.226+0000] {task_command.py:467} INFO - Running <TaskInstance: refresh_bike_db.install_requirements scheduled__2025-10-31T08:27:00+00:00 [running]> on host 8e61f8c083ab
[2025-10-31T08:28:01.228+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-31T08:28:01.385+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='refresh_bike_db' AIRFLOW_CTX_TASK_ID='install_requirements' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T08:27:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T08:27:00+00:00'
[2025-10-31T08:28:01.387+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-31T08:28:01.407+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T08:28:01.410+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n          set -euxo pipefail\n          cd "$AIRFLOW_HOME/plugins"\n          python -m pip install --no-cache-dir -r requirements.txt\n          python -m pip show folium\n          python -c "import folium, pandas, requests, pymysql; print(\'âœ… imports ok\')"\n        ']
[2025-10-31T08:28:01.422+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T08:28:01.424+0000] {subprocess.py:93} INFO - + cd /opt/***/plugins
[2025-10-31T08:28:01.425+0000] {subprocess.py:93} INFO - + python -m pip install --no-cache-dir -r requirements.txt
[2025-10-31T08:28:02.955+0000] {subprocess.py:93} INFO - 
[2025-10-31T08:28:02.956+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 24.2 -> 25.3
[2025-10-31T08:28:02.957+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2025-10-31T08:28:02.958+0000] {subprocess.py:93} INFO - ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
[2025-10-31T08:28:03.041+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T08:28:03.057+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T08:28:03.066+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=refresh_bike_db, task_id=install_requirements, run_id=scheduled__2025-10-31T08:27:00+00:00, execution_date=20251031T082700, start_date=20251031T082801, end_date=20251031T082803
[2025-10-31T08:28:03.091+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-31T08:28:03.092+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 340 for task install_requirements (Bash command failed. The command returned a non-zero exit code 1.; 6270)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T08:28:03.130+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-31T08:28:03.154+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T08:28:03.159+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
