[2025-10-30T15:23:33.038+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-30T15:23:33.081+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_bike_db.refresh_bike_db scheduled__2025-10-30T15:22:00+00:00 [queued]>
[2025-10-30T15:23:33.093+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_bike_db.refresh_bike_db scheduled__2025-10-30T15:22:00+00:00 [queued]>
[2025-10-30T15:23:33.094+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-10-30T15:23:33.116+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): refresh_bike_db> on 2025-10-30 15:22:00+00:00
[2025-10-30T15:23:33.129+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2879) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-30T15:23:33.129+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'refresh_bike_db', 'refresh_bike_db', 'scheduled__2025-10-30T15:22:00+00:00', '--job-id', '244', '--raw', '--subdir', 'DAGS_FOLDER/refresh_bike_db.py', '--cfg-path', '/tmp/tmpufas639g']
[2025-10-30T15:23:33.133+0000] {standard_task_runner.py:72} INFO - Started process 2880 to run task
[2025-10-30T15:23:33.133+0000] {standard_task_runner.py:105} INFO - Job 244: Subtask refresh_bike_db
[2025-10-30T15:23:33.159+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-30T15:23:33.233+0000] {task_command.py:467} INFO - Running <TaskInstance: refresh_bike_db.refresh_bike_db scheduled__2025-10-30T15:22:00+00:00 [running]> on host 8e61f8c083ab
[2025-10-30T15:23:33.237+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-30T15:23:33.372+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='refresh_bike_db' AIRFLOW_CTX_TASK_ID='refresh_bike_db' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T15:22:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-30T15:22:00+00:00'
[2025-10-30T15:23:33.374+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-30T15:23:33.396+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-30T15:23:33.398+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            set -exo pipefail\n            echo "PWD=$(pwd)"\n            echo "AIRFLOW_HOME=${AIRFLOW_HOME:-<unset>}"\n            python --version\n            which python\n            ls -lah "$AIRFLOW_HOME/plugins" || true\n\n            echo "DB env:"\n            echo "DB_HOST=${DB_HOST:-<unset>}"\n            echo "DB_PORT=${DB_PORT:-<unset>}"\n            echo "DB_USER=${DB_USER:-<unset>}"\n            echo "DB_NAME=${DB_NAME:-<unset>}"\n            if [ -z "${DB_PWD+x}" ]; then echo "DB_PWD=<unset>"; else echo "DB_PWD=<set>"; fi\n\n            cd "$AIRFLOW_HOME/plugins"\n\n            # Optionnel : self-test verbeux dans ton script (si tu l\'as ajouté)\n            # python gather_bike_data.py --self-test --verbose\n\n            # Exécution réelle\n            python gather_bike_data.py\n        ']
[2025-10-30T15:23:33.409+0000] {subprocess.py:86} INFO - Output:
[2025-10-30T15:23:33.411+0000] {subprocess.py:93} INFO - ++ pwd
[2025-10-30T15:23:33.412+0000] {subprocess.py:93} INFO - + echo PWD=/tmp/***tmpf62ag7il
[2025-10-30T15:23:33.412+0000] {subprocess.py:93} INFO - PWD=/tmp/***tmpf62ag7il
[2025-10-30T15:23:33.413+0000] {subprocess.py:93} INFO - + echo AIRFLOW_HOME=/opt/***
[2025-10-30T15:23:33.413+0000] {subprocess.py:93} INFO - AIRFLOW_HOME=/opt/***
[2025-10-30T15:23:33.414+0000] {subprocess.py:93} INFO - + python --version
[2025-10-30T15:23:33.414+0000] {subprocess.py:93} INFO - Python 3.12.6
[2025-10-30T15:23:33.415+0000] {subprocess.py:93} INFO - + which python
[2025-10-30T15:23:33.416+0000] {subprocess.py:93} INFO - /usr/local/bin/python
[2025-10-30T15:23:33.417+0000] {subprocess.py:93} INFO - + ls -lah /opt/***/plugins
[2025-10-30T15:23:33.423+0000] {subprocess.py:93} INFO - total 16K
[2025-10-30T15:23:33.424+0000] {subprocess.py:93} INFO - drwxrwxrwx 1 root    root  512 Oct 30 14:29 .
[2025-10-30T15:23:33.424+0000] {subprocess.py:93} INFO - drwxrwxr-x 1 *** root 4.0K Oct 30 13:10 ..
[2025-10-30T15:23:33.425+0000] {subprocess.py:93} INFO - -rwxrwxrwx 1 root    root  156 Oct 30 14:39 .env
[2025-10-30T15:23:33.426+0000] {subprocess.py:93} INFO - -rwxrwxrwx 1 root    root  11K Oct 30 14:58 gather_bike_data.py
[2025-10-30T15:23:33.427+0000] {subprocess.py:93} INFO - + echo 'DB env:'
[2025-10-30T15:23:33.427+0000] {subprocess.py:93} INFO - DB env:
[2025-10-30T15:23:33.428+0000] {subprocess.py:93} INFO - + echo DB_HOST=host.docker.internal
[2025-10-30T15:23:33.429+0000] {subprocess.py:93} INFO - DB_HOST=host.docker.internal
[2025-10-30T15:23:33.429+0000] {subprocess.py:93} INFO - + echo DB_PORT=3306
[2025-10-30T15:23:33.430+0000] {subprocess.py:93} INFO - DB_PORT=3306
[2025-10-30T15:23:33.431+0000] {subprocess.py:93} INFO - + echo DB_USER=root
[2025-10-30T15:23:33.431+0000] {subprocess.py:93} INFO - DB_USER=root
[2025-10-30T15:23:33.432+0000] {subprocess.py:93} INFO - + echo DB_NAME=renfpython
[2025-10-30T15:23:33.433+0000] {subprocess.py:93} INFO - DB_NAME=renfpython
[2025-10-30T15:23:33.433+0000] {subprocess.py:93} INFO - + '[' -z x ']'
[2025-10-30T15:23:33.434+0000] {subprocess.py:93} INFO - + echo 'DB_PWD=<set>'
[2025-10-30T15:23:33.434+0000] {subprocess.py:93} INFO - DB_PWD=<set>
[2025-10-30T15:23:33.435+0000] {subprocess.py:93} INFO - + cd /opt/***/plugins
[2025-10-30T15:23:33.435+0000] {subprocess.py:93} INFO - + python gather_bike_data.py
[2025-10-30T15:23:33.484+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-30T15:23:33.484+0000] {subprocess.py:93} INFO -   File "/opt/***/plugins/gather_bike_data.py", line 2, in <module>
[2025-10-30T15:23:33.486+0000] {subprocess.py:93} INFO -     import pymysql
[2025-10-30T15:23:33.487+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'pymysql'
[2025-10-30T15:23:33.490+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-30T15:23:33.504+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-30T15:23:33.510+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=refresh_bike_db, task_id=refresh_bike_db, run_id=scheduled__2025-10-30T15:22:00+00:00, execution_date=20251030T152200, start_date=20251030T152333, end_date=20251030T152333
[2025-10-30T15:23:33.527+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-30T15:23:33.528+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 244 for task refresh_bike_db (Bash command failed. The command returned a non-zero exit code 1.; 2880)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-30T15:23:33.551+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-30T15:23:33.573+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-30T15:23:33.579+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
