[2025-10-30T15:24:32.437+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-30T15:24:32.463+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_bike_db.refresh_bike_db scheduled__2025-10-30T15:23:00+00:00 [queued]>
[2025-10-30T15:24:32.478+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_bike_db.refresh_bike_db scheduled__2025-10-30T15:23:00+00:00 [queued]>
[2025-10-30T15:24:32.480+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-10-30T15:24:32.499+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): refresh_bike_db> on 2025-10-30 15:23:00+00:00
[2025-10-30T15:24:32.509+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2913) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-30T15:24:32.513+0000] {standard_task_runner.py:72} INFO - Started process 2914 to run task
[2025-10-30T15:24:32.510+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'refresh_bike_db', 'refresh_bike_db', 'scheduled__2025-10-30T15:23:00+00:00', '--job-id', '246', '--raw', '--subdir', 'DAGS_FOLDER/refresh_bike_db.py', '--cfg-path', '/tmp/tmpqsp6s8d3']
[2025-10-30T15:24:32.516+0000] {standard_task_runner.py:105} INFO - Job 246: Subtask refresh_bike_db
[2025-10-30T15:24:32.545+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-30T15:24:32.611+0000] {task_command.py:467} INFO - Running <TaskInstance: refresh_bike_db.refresh_bike_db scheduled__2025-10-30T15:23:00+00:00 [running]> on host 8e61f8c083ab
[2025-10-30T15:24:32.614+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-30T15:24:32.745+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='refresh_bike_db' AIRFLOW_CTX_TASK_ID='refresh_bike_db' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T15:23:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-30T15:23:00+00:00'
[2025-10-30T15:24:32.747+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-30T15:24:32.769+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-30T15:24:32.771+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            set -exo pipefail\n            echo "PWD=$(pwd)"\n            echo "AIRFLOW_HOME=${AIRFLOW_HOME:-<unset>}"\n            python --version\n            which python\n            ls -lah "$AIRFLOW_HOME/plugins" || true\n\n            echo "DB env:"\n            echo "DB_HOST=${DB_HOST:-<unset>}"\n            echo "DB_PORT=${DB_PORT:-<unset>}"\n            echo "DB_USER=${DB_USER:-<unset>}"\n            echo "DB_NAME=${DB_NAME:-<unset>}"\n            if [ -z "${DB_PWD+x}" ]; then echo "DB_PWD=<unset>"; else echo "DB_PWD=<set>"; fi\n\n            cd "$AIRFLOW_HOME/plugins"\n\n            # Optionnel : self-test verbeux dans ton script (si tu l\'as ajouté)\n            # python gather_bike_data.py --self-test --verbose\n\n            # Exécution réelle\n            python gather_bike_data.py\n        ']
[2025-10-30T15:24:32.783+0000] {subprocess.py:86} INFO - Output:
[2025-10-30T15:24:32.785+0000] {subprocess.py:93} INFO - ++ pwd
[2025-10-30T15:24:32.785+0000] {subprocess.py:93} INFO - + echo PWD=/tmp/***tmpg7128sre
[2025-10-30T15:24:32.786+0000] {subprocess.py:93} INFO - PWD=/tmp/***tmpg7128sre
[2025-10-30T15:24:32.787+0000] {subprocess.py:93} INFO - + echo AIRFLOW_HOME=/opt/***
[2025-10-30T15:24:32.788+0000] {subprocess.py:93} INFO - AIRFLOW_HOME=/opt/***
[2025-10-30T15:24:32.789+0000] {subprocess.py:93} INFO - + python --version
[2025-10-30T15:24:32.791+0000] {subprocess.py:93} INFO - Python 3.12.6
[2025-10-30T15:24:32.792+0000] {subprocess.py:93} INFO - + which python
[2025-10-30T15:24:32.794+0000] {subprocess.py:93} INFO - /usr/local/bin/python
[2025-10-30T15:24:32.795+0000] {subprocess.py:93} INFO - + ls -lah /opt/***/plugins
[2025-10-30T15:24:32.805+0000] {subprocess.py:93} INFO - total 16K
[2025-10-30T15:24:32.806+0000] {subprocess.py:93} INFO - drwxrwxrwx 1 root    root  512 Oct 30 14:29 .
[2025-10-30T15:24:32.807+0000] {subprocess.py:93} INFO - drwxrwxr-x 1 *** root 4.0K Oct 30 13:10 ..
[2025-10-30T15:24:32.808+0000] {subprocess.py:93} INFO - -rwxrwxrwx 1 root    root  156 Oct 30 14:39 .env
[2025-10-30T15:24:32.809+0000] {subprocess.py:93} INFO - -rwxrwxrwx 1 root    root  11K Oct 30 14:58 gather_bike_data.py
[2025-10-30T15:24:32.809+0000] {subprocess.py:93} INFO - + echo 'DB env:'
[2025-10-30T15:24:32.810+0000] {subprocess.py:93} INFO - DB env:
[2025-10-30T15:24:32.810+0000] {subprocess.py:93} INFO - + echo DB_HOST=host.docker.internal
[2025-10-30T15:24:32.811+0000] {subprocess.py:93} INFO - DB_HOST=host.docker.internal
[2025-10-30T15:24:32.811+0000] {subprocess.py:93} INFO - + echo DB_PORT=3306
[2025-10-30T15:24:32.812+0000] {subprocess.py:93} INFO - DB_PORT=3306
[2025-10-30T15:24:32.813+0000] {subprocess.py:93} INFO - + echo DB_USER=root
[2025-10-30T15:24:32.814+0000] {subprocess.py:93} INFO - DB_USER=root
[2025-10-30T15:24:32.815+0000] {subprocess.py:93} INFO - + echo DB_NAME=renfpython
[2025-10-30T15:24:32.816+0000] {subprocess.py:93} INFO - DB_NAME=renfpython
[2025-10-30T15:24:32.817+0000] {subprocess.py:93} INFO - + '[' -z x ']'
[2025-10-30T15:24:32.818+0000] {subprocess.py:93} INFO - + echo 'DB_PWD=<set>'
[2025-10-30T15:24:32.819+0000] {subprocess.py:93} INFO - DB_PWD=<set>
[2025-10-30T15:24:32.819+0000] {subprocess.py:93} INFO - + cd /opt/***/plugins
[2025-10-30T15:24:32.820+0000] {subprocess.py:93} INFO - + python gather_bike_data.py
[2025-10-30T15:24:32.864+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-30T15:24:32.865+0000] {subprocess.py:93} INFO -   File "/opt/***/plugins/gather_bike_data.py", line 2, in <module>
[2025-10-30T15:24:32.866+0000] {subprocess.py:93} INFO -     import pymysql
[2025-10-30T15:24:32.867+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'pymysql'
[2025-10-30T15:24:32.871+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-30T15:24:32.887+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-30T15:24:32.894+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=refresh_bike_db, task_id=refresh_bike_db, run_id=scheduled__2025-10-30T15:23:00+00:00, execution_date=20251030T152300, start_date=20251030T152432, end_date=20251030T152432
[2025-10-30T15:24:32.914+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-30T15:24:32.916+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 246 for task refresh_bike_db (Bash command failed. The command returned a non-zero exit code 1.; 2914)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-30T15:24:32.931+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-30T15:24:32.962+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-30T15:24:32.967+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
